name: Build & Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write   # perlu agar bisa push image ke GHCR

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & push image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}

  # ------ optional: deploy to VPS over SSH ------
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ secrets.SSH_HOST != '' }}
    steps:
    - name: Deploy on VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker pull ${{ env.IMAGE_NAME }}
          docker stop soilsense || true && docker rm soilsense || true
          docker run -d --restart unless-stopped --name soilsense -p 80:8000 ${{ env.IMAGE_NAME }}
